function Txx = TEamLaplacian(x,T)

N = size(T,1);
Txx = zeros(size(T));
j = [2:N-1];
Txx(j) = (2./(x(j+1)-x(j))).*(...
    ((T(j+1)-T(j))./(x(j+1)-x(j))) - ...
    ((T(j)-T(j-1))./(x(j)-x(j-1))) );
Txx(1) = 2*((x(2)-x(1))*(T(3)-T(1)) - ...
	    (x(3)-x(1))*(T(2)-T(1)))/...
	 ((x(3)-x(1))*(x(2)-x(1))*(x(3)-x(2)));
Txx(N) = 2*((x(N-1)-x(N))*(T(N-2)-T(N)) - ...
	    (x(N-2)-x(N))*(T(N-1)-T(N)))/...
	 ((x(N-2)-x(N))*(x(N-1)-x(N))*(x(N-2)-x(N-1)));

return
